# Generated by Django 4.0.3 on 2022-04-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atuendos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='marca')),
                ('talle', models.CharField(max_length=3, verbose_name='talle')),
                ('color', models.CharField(max_length=50, verbose_name='color')),
            ],
        ),
    ]
