# Generated by Django 4.0.3 on 2022-04-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atuendos', '0002_remera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pantalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='marca')),
                ('talle', models.IntegerField(verbose_name='talle')),
                ('tipo_de_tela', models.CharField(max_length=50, verbose_name='tela')),
            ],
        ),
    ]
